@name Cerberus_turret

@inputs 
@outputs 
@persist [E O]:entity [Q]:table



#include "AddHolo"
if(changed(0)) {
    
    
    
    timer("create", 1)
}

if(clk("create")) {
    
    local Step = Q["createStep", number]
    if(Step == 0) {
        
        
        timer("create", 1)
        Q["createStep", number] = Step + 1
    }
    elseif(Step == 1) {
        
        
        function addHoloBone(Bone_name:string, Bone_pos:vector, Bone_ang:angle, Bone_INTO:string) {
            
            addHolo(Bone_name + "_root", Bone_pos, vec(), Bone_ang, vec(), "cube", "", Bone_INTO       )
            addHolo(Bone_name          ,    vec(), vec(),    ang(), vec(), "cube", "", AddHolo_lastName)
        }
        
        
        E = entity()
        O = owner()
        addHolo("rt", vec(0,0,5),vec(), ang(),vec(), "cube", "", "") addHoloINTO(E)
        
        addHolo("base", vec(0,0,0),vec(), ang(),vec(), "cube", "", "rt")
        
        local Radius = 6
        local Height = 1
        local Clip = Height
        local Length = Radius/2 * sin(acos(Clip/Radius)) + 0.01
        
        local Height0 = Height * 0.5
        local Length0 = Length
        
        
        for(C = 1, 3) {
            local F = C - 1
            local A = 120 * F
            
            addHolo("", vec(),vec(Radius,Radius,Height), ang(),vec(255), "hq_tube_thin", "", "base")
            addHolo_clip(vec(),ang(0,90+A,0),Clip)
            addHolo_clip(vec(),ang(0,30+A,0),Clip)
            
            
            
            local LapaRT = "lapaRT" + C
            addHoloBone(LapaRT, vec(0,0,0), ang(0,A,0), "base")
            addHolo_offset(vec(10,0,0), ang())
            
            addHolo("", vec(Length,0,0),vec(Height,Height,Length), ang(90,0,0),vec(255), "hq_stube_thin", "", LapaRT + "_root")
            
            
            
            local Lenght_0 = Height * 0.25
            addHolo("", vec(-Lenght_0,0,0),vec(Height0,Height0,Lenght_0), ang(90,0,0),vec(255), "hq_stube_thin", "", LapaRT)
            addHolo("", vec(-Lenght_0*3,0,0),vec(Lenght_0,Height0,Height0), ang(0,0,0),vec(255), "cube", "", LapaRT)
            
            
            local LapaRT1 = LapaRT + "_root1"
            local Lapa_r1_R = max(Height0*0.1 ,0.025)
            local Lapa_r1_offset = Lapa_r1_R*0.5-Height0
            addHolo(LapaRT1, vec(0,0,Lapa_r1_offset),vec(), ang(),vec(), "cube", "", LapaRT)
            addHolo("", vec(0,0,0),vec(Lapa_r1_R,Lapa_r1_R,Height0 * 0.9), ang(0,0,90),vec(255), "hq_cylinder", "", LapaRT1)
            
            
        }
        
        addHolo("", vec(0,0,-Height-0.05),vec(Radius,Radius,0.05), ang(),vec(255), "hq_cylinder", "", "base")
        
        
        addHolo_timer("create")
        Q["createStep", number] = Step + 1
    }
    else {
        
    }
}



























































































